language: node_js
node_js:
  - '8'
cache: yarn

# In order to avoid double build on pull requests,
# only build on pushes on master and on pushes on pull requests
branches:
  only:
    - master

install:
  - yarn install

stages:
  - lint
  - integration

  # make sure that release only happens on master
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: integration
      script:
        - yarn test

    - stage: release
      script:
        - yarn pub
