cache: yarn
language: node_js

node_js:
  - 11

branches:
  only:
    - master

install:
  - yarn install

stages:
  - lint
  - integration

  # make sure that release only happens on master
  - name: release
    if: type != pull_request AND branch = master

jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: integration
      script:
        - yarn test

    - stage: release
      script:
        - git config --global author.login "vue-styleguidist-bot"
        - git remote set-url origin "https://${GH_TOKEN}@github.com/vue-styleguidist/vue-cli-plugin-styleguidist.git" > /dev/null 2>&1
        - git checkout master
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
        - yarn pub --amend --github-release
